-- KÔLÔ — schéma Supabase robuste
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text default '',
  phone text default '',
  city text default '',
  neighborhood text default '',
  avatar_url text,
  is_verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 3 and 100),
  description text default '',
  price numeric(12,2) not null default 0 check(price>=0),
  city text not null,
  neighborhood text not null,
  category text not null,
  emoji text default '📦',
  image_url text,
  seller_name text not null,
  seller_phone text,
  status text not null default 'active' check(status in('active','sold','hidden','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,listing_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint references public.listings(id) on delete set null,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  reason text not null,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists listings_city_idx on public.listings(city);
create index if not exists listings_category_idx on public.listings(category);
create index if not exists listings_status_idx on public.listings(status);
create index if not exists listings_created_idx on public.listings(created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id);
create index if not exists messages_receiver_idx on public.messages(receiver_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,phone,is_verified)
  values(
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    coalesce(new.raw_user_meta_data->>'phone',''),
    coalesce(new.email_confirmed_at is not null,false)
  )
  on conflict(id) do update set
    full_name=excluded.full_name,
    phone=excluded.phone;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists listings_updated_at on public.listings;
create trigger listings_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.listings enable row level security;
alter table public.favorites enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;

-- Profiles
 drop policy if exists profiles_public_read on public.profiles;
 drop policy if exists profile_own_read on public.profiles;
 create policy profile_own_read on public.profiles
 for select to authenticated using (id=(select auth.uid()));
 drop policy if exists profile_own_update on public.profiles;
 create policy profile_own_update on public.profiles
 for update to authenticated
 using (id=(select auth.uid()))
 with check (id=(select auth.uid()));

-- Listings: owner_id est UUID, donc auth.uid() reste UUID.
drop policy if exists listings_public_read on public.listings;
create policy listings_public_read on public.listings
for select to public
using (status='active' or owner_id=(select auth.uid()));
drop policy if exists listings_owner_insert on public.listings;
create policy listings_owner_insert on public.listings
for insert to authenticated
with check (owner_id=(select auth.uid()));
drop policy if exists listings_owner_update on public.listings;
create policy listings_owner_update on public.listings
for update to authenticated
using (owner_id=(select auth.uid()))
with check (owner_id=(select auth.uid()));
drop policy if exists listings_owner_delete on public.listings;
create policy listings_owner_delete on public.listings
for delete to authenticated
using (owner_id=(select auth.uid()));

-- Favorites
 drop policy if exists favorites_own_read on public.favorites;
 create policy favorites_own_read on public.favorites for select to authenticated using (user_id=(select auth.uid()));
 drop policy if exists favorites_own_insert on public.favorites;
 create policy favorites_own_insert on public.favorites for insert to authenticated with check (user_id=(select auth.uid()));
 drop policy if exists favorites_own_delete on public.favorites;
 create policy favorites_own_delete on public.favorites for delete to authenticated using (user_id=(select auth.uid()));

-- Messages
 drop policy if exists messages_participant_read on public.messages;
 create policy messages_participant_read on public.messages for select to authenticated using (sender_id=(select auth.uid()) or receiver_id=(select auth.uid()));
 drop policy if exists messages_sender_insert on public.messages;
 create policy messages_sender_insert on public.messages for insert to authenticated with check (sender_id=(select auth.uid()));

-- Reports
 drop policy if exists reports_own_read on public.reports;
 create policy reports_own_read on public.reports for select to authenticated using (reporter_id=(select auth.uid()));
 drop policy if exists reports_user_insert on public.reports;
 create policy reports_user_insert on public.reports for insert to authenticated with check (reporter_id=(select auth.uid()));

-- Storage
insert into storage.buckets(id,name,public)
values('listing-images','listing-images',true)
on conflict(id) do update set public=true;

drop policy if exists listing_images_public_read on storage.objects;
create policy listing_images_public_read on storage.objects
for select to public
using (bucket_id='listing-images');

-- IMPORTANT : storage.objects.owner_id peut être text ou uuid selon la version/schema Storage.
-- On ne le compare donc jamais à auth.uid(). Le chemin du fichier fait foi:
-- listing-images/<UUID_UTILISATEUR>/<fichier>
drop policy if exists listing_images_user_upload on storage.objects;
create policy listing_images_user_upload on storage.objects
for insert to authenticated
with check (
  bucket_id='listing-images'
  and (storage.foldername(name))[1]=(select auth.uid()::text)
);

drop policy if exists listing_images_user_update on storage.objects;
create policy listing_images_user_update on storage.objects
for update to authenticated
using (
  bucket_id='listing-images'
  and (storage.foldername(name))[1]=(select auth.uid()::text)
)
with check (
  bucket_id='listing-images'
  and (storage.foldername(name))[1]=(select auth.uid()::text)
);

drop policy if exists listing_images_user_delete on storage.objects;
create policy listing_images_user_delete on storage.objects
for delete to authenticated
using (
  bucket_id='listing-images'
  and (storage.foldername(name))[1]=(select auth.uid()::text)
);
